### ISSUE TITLE
Warnings about rule namespaces for Capybara and FactoryBot

### ISSUE THREAD

**Issue by geoffswift** [airbnb/ruby#211]
I am seeing some warnings about the namespace for a few rules:

```
usr/local/rvm/gems/ruby-3.1.4/gems/rubocop-airbnb-7.0.0/config/rubocop-rspec.yml: RSpec/Capybara/CurrentPathExpectation has the wrong namespace - replace it with Capybara/CurrentPathExpectation
/usr/local/rvm/gems/ruby-3.1.4/gems/rubocop-airbnb-7.0.0/config/rubocop-rspec.yml: RSpec/FactoryBot/AttributeDefinedStatically has the wrong namespace - replace it with FactoryBot/AttributeDefinedStatically
/usr/local/rvm/gems/ruby-3.1.4/gems/rubocop-airbnb-7.0.0/config/rubocop-rspec.yml: RSpec/FactoryBot/CreateList has the wrong namespace - replace it with FactoryBot/CreateList
```

My `Gemfile.lock` tells me I have these versions installed:

rubocop-capybara (2.21.0)
rubocop-factory_bot (2.26.1)

**Comment by geoffswift** [comment]
I just noticed this is being addressed in #208 👍

**Comment by santiagorodriguez96** [comment]
This was addressed as part of https://github.com/airbnb/ruby/pull/212 🙂

**Comment by mitorez** [comment]
There is still an issue with `Capybara/CurrentPathExpectation`...
```
Error: The `Capybara/CurrentPathExpectation` cop has been moved to `Capybara/RSpec/CurrentPathExpectation`.
(obsolete configuration found in /Users/USERNAME/.rbenv/versions/3.2.11/lib/ruby/gems/3.2.0/gems/rubocop-airbnb-8.1.0/config/rubocop-capybara.yml, please update it)
```

Environment:
- macOS 26.5
- rbenv 1.3.2
- Ruby 3.2.11
- rubocop-airbnb 8.1.0
- rubocop-capybara 2.23.0
